function out1 = M_BICB_Q(fi12,fi13)
%M_BICB_Q
%    OUT1 = M_BICB_Q(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:42:46

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = t2.*3.196e-1;
t7 = t4.*3.196e-1;
t8 = t3.*6.31e-2;
t9 = t5.*6.31e-2;
t10 = t6+t8-1.0./1.0e+2;
t14 = t7+t9-3.55e-2;
t11 = abs(t10);
t12 = sign(t10);
t15 = abs(t14);
t16 = sign(t14);
t13 = t11.^2;
t17 = t15.^2;
t18 = t13+t17;
t19 = 1.0./sqrt(t18);
out1 = [(t19.*(t4.*t11.*t12.*6.392e-1-t2.*t15.*t16.*6.392e-1))./2.0;(t19.*(t5.*t11.*t12.*1.262e-1-t3.*t15.*t16.*1.262e-1))./2.0];
end
