function LM_total_sym = M_BICB_LM(fi12,fi13)
%M_BICB_LM
%    LM_total_sym = M_BICB_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:42:46

LM_total_sym = sqrt(abs(cos(fi12).*3.196e-1+cos(fi13).*6.31e-2-1.0./1.0e+2).^2+abs(sin(fi12).*3.196e-1+sin(fi13).*6.31e-2-3.55e-2).^2);
end
