function LM_total_sym = M_CORB_LM(fi12)
%M_CORB_LM
%    LM_total_sym = M_CORB_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:43

LM_total_sym = sqrt(abs(cos(fi12).*1.533e-1-2.96e-2).^2+abs(sin(fi12)).^2.*2.350089e-2);
end
