function LM_total_sym = M_DELT_LM(fi12)
%M_DELT_LM
%    LM_total_sym = M_DELT_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:38

LM_total_sym = sqrt(abs(cos(fi12).*1.091e-1-3.96e-2).^2+abs(sin(fi12).*1.091e-1-2.83e-2).^2);
end
