function out1 = M_DELT_Q(fi12)
%M_DELT_Q
%    OUT1 = M_DELT_Q(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:38

t2 = cos(fi12);
t3 = sin(fi12);
t4 = t2.*1.091e-1;
t5 = t3.*1.091e-1;
t6 = t4-3.96e-2;
t7 = t5-2.83e-2;
t8 = abs(t6);
t9 = abs(t7);
out1 = [(1.0./sqrt(t8.^2+t9.^2).*(t3.*t8.*sign(t6).*2.182e-1-t2.*t9.*sign(t7).*2.182e-1))./2.0;0.0];
end
