function vM_total_sym = M_TMAJ_vM(fi12,fi12_dot)
%M_TMAJ_vM
%    vM_total_sym = M_TMAJ_vM(FI12,FI12_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:32

t2 = cos(fi12);
t3 = sin(fi12);
t4 = t2.*4.21e-2;
t5 = t3.*4.21e-2;
t6 = t4+5.83e-2;
t7 = t5+7.33e-2;
vM_total_sym = (fi12_dot.*1.0./sqrt(t6.^2+t7.^2).*(t2.*t7.*8.42e-2-t3.*t6.*8.42e-2))./2.0;
end
