function out1 = M_TMAJ_Q(fi12)
%M_TMAJ_Q
%    OUT1 = M_TMAJ_Q(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:32

t2 = cos(fi12);
t3 = sin(fi12);
t4 = t2.*4.21e-2;
t5 = t3.*4.21e-2;
t6 = t4+5.83e-2;
t7 = t5+7.33e-2;
out1 = [1.0./sqrt(t6.^2+t7.^2).*(t2.*t7.*8.42e-2-t3.*t6.*8.42e-2).*(-1.0./2.0);0.0];
end
