function LM_total_sym = M_TMAJ_LM(fi12)
%M_TMAJ_LM
%    LM_total_sym = M_TMAJ_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 17:52:32

LM_total_sym = sqrt((cos(fi12).*4.21e-2+5.83e-2).^2+(sin(fi12).*4.21e-2+7.33e-2).^2);
end
