function theta_raw = M_TRIPB_CMED_theta(fi12,fi13)
%M_TRIPB_CMED_theta
%    THETA_RAW = M_TRIPB_CMED_theta(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 18:37:33

theta_raw = -fi12+fi13-pi-2.443587721703193;
end
