function vM_total_sym = M_TRIPB_CMED_vM(fi12,fi13,fi12_dot,fi13_dot)
%M_TRIPB_CMED_vM
%    vM_total_sym = M_TRIPB_CMED_vM(FI12,FI13,FI12_DOT,FI13_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 23:41:35

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = -fi13;
t7 = fi12+t6;
t13 = t3.*2.515027624309392e-2;
t14 = t5.*2.515027624309392e-2;
t19 = t3.*1.667044105283557e-2;
t20 = t5.*1.667044105283557e-2;
t21 = t2.*1.987320944803853e-2;
t22 = t4.*1.987320944803853e-2;
t25 = t2.*1.756515458122541e-1;
t26 = t4.*1.756515458122541e-1;
t8 = cos(t7);
t9 = sin(t7);
t23 = -t20;
t24 = -t21;
t27 = t14+t19;
t33 = t22+t25;
t10 = t8.^2;
t11 = t9.^2;
t28 = abs(t27);
t29 = t13+t23;
t34 = t24+t26;
t35 = abs(t33);
t12 = 1.0./t10;
t15 = t10+t11;
t30 = abs(t29);
t36 = abs(t34);
t16 = t11.*t12;
t18 = 1.0./t15;
t17 = t16+1.0;
t31 = (t10.*t17.*t18)./5.0e+1;
vM_total_sym = fi13_dot.*(t31+(1.0./sqrt(t28.^2+t30.^2).*(t28.*t29.*sign(t27).*2.0-t27.*t30.*sign(t29).*2.0))./2.0)-fi12_dot.*(t31+(1.0./sqrt(t35.^2+t36.^2).*(t34.*t35.*sign(t33).*2.0-t33.*t36.*sign(t34).*2.0))./2.0);
end
