function LM_total_sym = M_TRIPB_CLONG_LM(fi12,fi13)
%M_TRIPB_CLONG_LM
%    LM_total_sym = M_TRIPB_CLONG_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Mar-2025 01:07:06

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = -fi13;
t7 = fi12+t6;
t11 = t2.*1.53e-2;
t12 = t2.*2.31e-2;
t13 = t4.*1.53e-2;
t14 = t4.*2.31e-2;
t17 = t3.*2.515027624309392e-2;
t18 = t5.*2.515027624309392e-2;
t27 = t3.*1.667044105283557e-2;
t28 = t5.*1.667044105283557e-2;
t8 = cos(t7);
t9 = sin(t7);
t16 = -t14;
t25 = t12+t13+3.196e-1;
t29 = -t28;
t30 = t18+t27;
t10 = t9.*1i;
t22 = t11+t16;
t26 = t25.^2;
t32 = t17+t29;
t15 = -t10;
t23 = abs(t22);
t33 = abs(t32);
t19 = t8+t15;
t24 = t23.^2;
t35 = t33.^2;
t20 = angle(t19);
t36 = t24+t26;
t21 = t20./5.0e+1;
if ~all(cellfun(@isscalar,{t20}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t20 < 0.0)
    LM_total_sym = t21+pi./2.5e+1+sqrt(t35+abs(t30).^2)+sqrt(abs((t2.*sin(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1)))./5.0e+1+t4.*(cos(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1))./5.0e+1-3.196e-1)-1.53e-2).^2+abs((t4.*sin(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1)))./5.0e+1-t2.*(cos(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1))./5.0e+1-3.196e-1)+2.31e-2).^2);
else
    LM_total_sym = t21+sqrt(t35+abs(t30).^2)+sqrt(abs((t2.*sin(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1)))./5.0e+1+t4.*(cos(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1))./5.0e+1-3.196e-1)-1.53e-2).^2+abs((t4.*sin(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1)))./5.0e+1-t2.*(cos(acos(t25.*1.0./sqrt(t36))+acos(1.0./sqrt(t36)./5.0e+1))./5.0e+1-3.196e-1)+2.31e-2).^2);
end
end
