function theta = M_TRIPB_CLAT_theta(fi12,fi13)
%M_TRIPB_CLAT_theta
%    THETA = M_TRIPB_CLAT_theta(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Mar-2025 18:58:43

theta = -fi12+fi13-pi-2.475759714855882;
end
