function [p1A_subs,p1B_subs,dummy] = M_BICB_points(fi12,fi13)
%M_BICB_points
%    [p1A_subs,p1B_subs,DUMMY] = M_BICB_points(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = NaN;
t3 = cos(fi13);
t4 = sin(fi13);
p1A_subs = [t3.*3.609e-2-t4.*1.072e-2+cos(fi12).*(2.9e+1./1.0e+2);t3.*1.072e-2+t4.*3.609e-2+sin(fi12).*(2.9e+1./1.0e+2)];
if nargout > 1
    p1B_subs = [-1.02e-3;2.051e-2];
end
if nargout > 2
    dummy = [t2;t2];
end
end
