function [p1A_subs,p1B_subs,dummy] = M_BRACH_points(fi12,fi13)
%M_BRACH_points
%    [p1A_subs,p1B_subs,DUMMY] = M_BRACH_points(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = NaN;
t3 = cos(fi12);
t4 = cos(fi13);
t5 = sin(fi12);
t6 = sin(fi13);
p1A_subs = [t3.*(2.9e+1./1.0e+2)+t4.*4.166e-2-t6.*4.6e-3;t4.*4.6e-3+t5.*(2.9e+1./1.0e+2)+t6.*4.166e-2];
if nargout > 1
    p1B_subs = [t3.*1.9078e-1-t5.*1.039999999999976e-3;t3.*1.039999999999976e-3+t5.*1.9078e-1];
end
if nargout > 2
    dummy = [t2;t2];
end
end
