function [p1A_subs,p1B_subs,dummy] = M_DELT_points(fi12)
%M_DELT_points
%    [p1A_subs,p1B_subs,DUMMY] = M_DELT_points(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:07

t2 = NaN;
t3 = cos(fi12);
t4 = sin(fi12);
p1A_subs = [t3.*9.231e-2-t4.*8.63e-3;t3.*8.63e-3+t4.*9.231e-2];
if nargout > 1
    p1B_subs = [1.18e-3;3.124e-2];
end
if nargout > 2
    dummy = [t2;t2];
end
end
