function [p1A_subs,p1B_subs,dummy] = M_TMAJ_points(fi12)
%M_TMAJ_points
%    [p1A_subs,p1B_subs,DUMMY] = M_TMAJ_points(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:07

t2 = NaN;
t3 = cos(fi12);
t4 = sin(fi12);
p1A_subs = [t3.*7.838e-2-t4.*8.99e-3;t3.*8.99e-3+t4.*7.838e-2];
if nargout > 1
    p1B_subs = [-4.399e-2;-6.707e-2];
end
if nargout > 2
    dummy = [t2;t2];
end
end
