function [p1A_subs,p1B_subs,p1W_subs] = M_TRIPB_CLONG_points(fi12,fi13)
%M_TRIPB_CLONG_points
%    [p1A_subs,p1B_subs,p1W_subs] = M_TRIPB_CLONG_points(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:10

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = sqrt(3.0);
p1A_subs = [t2.*(2.9e+1./1.0e+2)+t3./1.0e+2+(t5.*t6)./1.0e+2;t4.*(2.9e+1./1.0e+2)+t5./1.0e+2-(t3.*t6)./1.0e+2];
if nargout > 1
    p1B_subs = [-1.603e-2;-1.611e-2];
end
if nargout > 2
    t7 = t2.*1.603e-2;
    t8 = t2.*1.611e-2;
    t9 = t4.*1.603e-2;
    t10 = t4.*1.611e-2;
    t11 = -t9;
    t15 = t7+t10+2.9e+1./1.0e+2;
    t12 = t8+t11;
    t16 = t15.^2;
    t13 = abs(t12);
    t14 = t13.^2;
    t17 = t14+t16;
    t18 = 1.0./sqrt(t17);
    t19 = t18./5.0e+1;
    t21 = t15.*t18;
    t20 = acos(t19);
    t22 = acos(t21);
    t23 = t20+t22;
    t24 = cos(t23);
    t25 = sin(t23);
    t26 = t24./5.0e+1;
    t27 = t26-2.9e+1./1.0e+2;
    p1W_subs = [-t2.*t27+(t4.*t25)./5.0e+1;t2.*t25.*(-1.0./5.0e+1)-t4.*t27];
end
end
