function [p1A_subs,p1B_subs,p1W_subs] = M_TRIPB_CLAT_points(fi12,fi13)
%M_TRIPB_CLAT_points
%    [p1A_subs,p1B_subs,p1W_subs] = M_TRIPB_CLAT_points(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:08

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = sqrt(3.0);
p1A_subs = [t2.*(2.9e+1./1.0e+2)+t3./1.0e+2+(t5.*t6)./1.0e+2;t4.*(2.9e+1./1.0e+2)+t5./1.0e+2-(t3.*t6)./1.0e+2];
if nargout > 1
    p1B_subs = [t2.*5.495e-2+t4.*(1.1e+1./1.0e+3);t2.*(-1.1e+1./1.0e+3)+t4.*5.495e-2];
end
if nargout > 2
    p1W_subs = [t2.*2.882982344182089e-1+t4.*1.992746832652435e-2;t2.*(-1.992746832652435e-2)+t4.*2.882982344182089e-1];
end
end
