function LM_total_sym = M_BICB_LM(fi12,fi13)
%M_BICB_LM
%    LM_total_sym = M_BICB_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi13);
t3 = sin(fi13);
LM_total_sym = sqrt(abs(t2.*1.072e-2+t3.*3.609e-2+sin(fi12).*(2.9e+1./1.0e+2)-2.051e-2).^2+abs(t2.*3.609e-2-t3.*1.072e-2+cos(fi12).*(2.9e+1./1.0e+2)+1.02e-3).^2);
end
