function out1 = M_BICB_Q(fi12,fi13)
%M_BICB_Q
%    OUT1 = M_BICB_Q(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = t2.*(2.9e+1./1.0e+2);
t7 = t4.*(2.9e+1./1.0e+2);
t8 = t3.*1.072e-2;
t9 = t5.*1.072e-2;
t11 = t3.*3.609e-2;
t12 = t5.*3.609e-2;
t10 = -t9;
t17 = t7+t8+t12-2.051e-2;
t13 = t6+t10+t11+1.02e-3;
t18 = abs(t17);
t19 = sign(t17);
t14 = abs(t13);
t15 = sign(t13);
t20 = t18.^2;
t16 = t14.^2;
t21 = t16+t20;
t22 = 1.0./sqrt(t21);
out1 = [(t22.*(t4.*t14.*t15.*(2.9e+1./5.0e+1)-t2.*t18.*t19.*(2.9e+1./5.0e+1)))./2.0;(t22.*(t14.*t15.*(t8+t12).*2.0-t18.*t19.*(t10+t11).*2.0))./2.0];
end
