function vM_total_sym = M_BRACH_vM(fi12,fi13,fi12_dot,fi13_dot)
%M_BRACH_vM
%    vM_total_sym = M_BRACH_vM(FI12,FI13,FI12_DOT,FI13_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
t6 = t3.*4.6e-3;
t7 = t5.*4.6e-3;
t9 = t3.*4.166e-2;
t10 = t2.*9.922e-2;
t11 = t5.*4.166e-2;
t12 = t4.*9.922e-2;
t13 = t2.*1.039999999999976e-3;
t14 = t4.*1.039999999999976e-3;
t8 = -t7;
t15 = -t13;
t16 = t8+t9+t10+t14;
t17 = t6+t11+t12+t15;
t18 = abs(t16);
t19 = abs(t17);
t20 = sign(t16);
t21 = sign(t17);
t22 = t18.^2;
t23 = t19.^2;
t24 = t22+t23;
t25 = 1.0./sqrt(t24);
vM_total_sym = fi13_dot.*t25.*(t18.*t20.*(t6+t11).*2.0-t19.*t21.*(t8+t9).*2.0).*(-1.0./2.0)+(fi12_dot.*t25.*(t19.*t21.*(t10+t14).*2.0-t18.*t20.*(t12+t15).*2.0))./2.0;
end
