function LM_total_sym = M_BRACH_LM(fi12,fi13)
%M_BRACH_LM
%    LM_total_sym = M_BRACH_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi12);
t3 = cos(fi13);
t4 = sin(fi12);
t5 = sin(fi13);
LM_total_sym = sqrt(abs(t2.*(-1.039999999999976e-3)+t3.*4.6e-3+t4.*9.922e-2+t5.*4.166e-2).^2+abs(t2.*9.922e-2+t3.*4.166e-2+t4.*1.039999999999976e-3-t5.*4.6e-3).^2);
end
