function vM_total_sym = M_CORB_vM(fi12,fi12_dot)
%M_CORB_vM
%    vM_total_sym = M_CORB_vM(FI12,FI12_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi12);
t3 = sin(fi12);
t4 = t2.*1.76e-3;
t5 = t3.*1.76e-3;
t6 = t2.*1.6485e-1;
t7 = t3.*1.6485e-1;
t8 = -t6;
t9 = t4+t7-8.06e-3;
t10 = abs(t9);
t11 = t5+t8+3.467e-2;
t12 = abs(t11);
vM_total_sym = fi12_dot.*1.0./sqrt(t10.^2+t12.^2).*(t10.*sign(t9).*(t5+t8).*2.0-t12.*sign(t11).*(t4+t7).*2.0).*(-1.0./2.0);
end
