function LM_total_sym = M_CORB_LM(fi12)
%M_CORB_LM
%    LM_total_sym = M_CORB_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:06

t2 = cos(fi12);
t3 = sin(fi12);
LM_total_sym = sqrt(abs(t2.*1.76e-3+t3.*1.6485e-1-8.06e-3).^2+abs(t2.*(-1.6485e-1)+t3.*1.76e-3+3.467e-2).^2);
end
