function LM_total_sym = M_DELT_LM(fi12)
%M_DELT_LM
%    LM_total_sym = M_DELT_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:07

t2 = cos(fi12);
t3 = sin(fi12);
LM_total_sym = sqrt(abs(t2.*8.63e-3+t3.*9.231e-2-3.124e-2).^2+abs(t2.*(-9.231e-2)+t3.*8.63e-3+1.18e-3).^2);
end
