function vM_total_sym = M_TMAJ_vM(fi12,fi12_dot)
%M_TMAJ_vM
%    vM_total_sym = M_TMAJ_vM(FI12,FI12_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:07

t2 = cos(fi12);
t3 = sin(fi12);
t4 = t2.*7.838e-2;
t5 = t3.*7.838e-2;
t6 = t2.*8.99e-3;
t7 = t3.*8.99e-3;
t8 = -t7;
t9 = t5+t6+6.707e-2;
t10 = abs(t9);
t11 = t4+t8+4.399e-2;
t12 = abs(t11);
vM_total_sym = (fi12_dot.*1.0./sqrt(t10.^2+t12.^2).*(t10.*sign(t9).*(t4+t8).*2.0-t12.*sign(t11).*(t5+t6).*2.0))./2.0;
end
