function LM_total_sym = M_TMAJ_LM(fi12)
%M_TMAJ_LM
%    LM_total_sym = M_TMAJ_LM(FI12)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:07

t2 = cos(fi12);
t3 = sin(fi12);
LM_total_sym = sqrt(abs(t2.*7.838e-2-t3.*8.99e-3+4.399e-2).^2+abs(t2.*8.99e-3+t3.*7.838e-2+6.707e-2).^2);
end
