function LM_total_sym = M_TRIPB_CLAT_LM(fi12,fi13)
%M_TRIPB_CLAT_LM
%    LM_total_sym = M_TRIPB_CLAT_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:08

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t13 = t3.*2.333482344182089e-1;
t14 = t2.*8.927468326524349e-3;
t15 = t3.*8.927468326524349e-3;
t16 = t2.*2.333482344182089e-1;
t6 = cos(t5);
t7 = sin(t5);
t17 = -t14;
t18 = t15+t16;
t8 = t7.*1i;
t20 = t13+t17;
t9 = -t8;
t10 = t6+t9;
t11 = angle(t10);
t12 = t11./5.0e+1;
if ~all(cellfun(@isscalar,{t11}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t11 < 0.0)
    LM_total_sym = t12+pi./2.5e+1+sqrt(abs(t18).^2+abs(t20).^2);
else
    LM_total_sym = t12+sqrt(abs(t18).^2+abs(t20).^2);
end
end
