function LM_total_sym = M_TRIPB_CMED_LM(fi12,fi13)
%M_TRIPB_CMED_LM
%    LM_total_sym = M_TRIPB_CMED_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:10

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t10 = t2.*3.985435215946844e-2;
t11 = t3.*3.985435215946844e-2;
t15 = t2.*4.983850992823741e-3;
t16 = t3.*4.983850992823741e-3;
t6 = cos(t5);
t7 = sin(t5);
t17 = -t15;
t18 = t10+t16;
t8 = t7.*1i;
t19 = t11+t17;
t20 = abs(t18);
t9 = -t8;
t22 = t20.^2;
t12 = t6+t9;
t13 = angle(t12);
t14 = t13./5.0e+1;
if ~all(cellfun(@isscalar,{t13}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t13 < 0.0)
    LM_total_sym = t14+pi./2.5e+1+sqrt(t22+abs(t19).^2);
else
    LM_total_sym = t14+sqrt(t22+abs(t19).^2);
end
end
