function LM_total_sym = M_TRIPB_CLONG_LM(fi12,fi13)
%M_TRIPB_CLONG_LM
%    LM_total_sym = M_TRIPB_CLONG_LM(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:08

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t10 = t2.*1.603e-2;
t11 = t2.*1.611e-2;
t12 = t3.*1.603e-2;
t13 = t3.*1.611e-2;
t6 = cos(t5);
t7 = sin(t5);
t14 = -t12;
t21 = t10+t13+2.9e+1./1.0e+2;
t8 = t7.*1i;
t18 = t11+t14;
t22 = t21.^2;
t9 = -t8;
t19 = abs(t18);
t15 = t6+t9;
t20 = t19.^2;
t16 = angle(t15);
t23 = t20+t22;
t17 = t16./5.0e+1;
if ~all(cellfun(@isscalar,{t16}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t16 < 0.0)
    LM_total_sym = t17+pi./2.5e+1+sqrt(abs((t3.*sin(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1)))./5.0e+1-t2.*(cos(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1))./5.0e+1-2.9e+1./1.0e+2)+1.603e-2).^2+abs((t2.*sin(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1)))./5.0e+1+t3.*(cos(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1))./5.0e+1-2.9e+1./1.0e+2)-1.611e-2).^2);
else
    LM_total_sym = t17+sqrt(abs((t3.*sin(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1)))./5.0e+1-t2.*(cos(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1))./5.0e+1-2.9e+1./1.0e+2)+1.603e-2).^2+abs((t2.*sin(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1)))./5.0e+1+t3.*(cos(acos(t21.*1.0./sqrt(t23))+acos(1.0./sqrt(t23)./5.0e+1))./5.0e+1-2.9e+1./1.0e+2)-1.611e-2).^2);
end
end
