function vM_total_sym = M_TRIPB_CLAT_vM(fi12,fi13,fi12_dot,fi13_dot)
%M_TRIPB_CLAT_vM
%    vM_total_sym = M_TRIPB_CLAT_vM(FI12,FI13,FI12_DOT,FI13_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:08

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t15 = t3.*2.333482344182089e-1;
t16 = t2.*8.927468326524349e-3;
t17 = t3.*8.927468326524349e-3;
t18 = t2.*2.333482344182089e-1;
t6 = cos(t5);
t7 = sin(t5);
t19 = -t16;
t20 = t17+t18;
t8 = t6.^2;
t9 = t7.^2;
t21 = abs(t20);
t22 = t15+t19;
t10 = 1.0./t8;
t11 = t8+t9;
t23 = abs(t22);
t12 = t9.*t10;
t14 = 1.0./t11;
t13 = t12+1.0;
vM_total_sym = -fi12_dot.*((1.0./sqrt(t21.^2+t23.^2).*(t21.*t22.*sign(t20).*2.0-t20.*t23.*sign(t22).*2.0))./2.0+(t8.*t13.*t14)./5.0e+1)+(fi13_dot.*t8.*t13.*t14)./5.0e+1;
end
