function out1 = M_TRIPB_CLAT_Q(fi12,fi13)
%M_TRIPB_CLAT_Q
%    OUT1 = M_TRIPB_CLAT_Q(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:08

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t15 = t3.*2.333482344182089e-1;
t16 = t2.*8.927468326524349e-3;
t17 = t3.*8.927468326524349e-3;
t18 = t2.*2.333482344182089e-1;
t6 = cos(t5);
t7 = sin(t5);
t19 = -t16;
t21 = t17+t18;
t8 = t6.^2;
t9 = t7.^2;
t22 = abs(t21);
t23 = t15+t19;
t10 = 1.0./t8;
t11 = t8+t9;
t24 = abs(t23);
t12 = t9.*t10;
t14 = 1.0./t11;
t13 = t12+1.0;
t20 = (t8.*t13.*t14)./5.0e+1;
out1 = [t20+(1.0./sqrt(t22.^2+t24.^2).*(t22.*t23.*sign(t21).*2.0-t21.*t24.*sign(t23).*2.0))./2.0;-t20];
end
