function vM_total_sym = M_TRIPB_CMED_vM(fi12,fi13,fi12_dot,fi13_dot)
%M_TRIPB_CMED_vM
%    vM_total_sym = M_TRIPB_CMED_vM(FI12,FI13,FI12_DOT,FI13_DOT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:10

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t11 = t2.*3.985435215946844e-2;
t12 = t3.*3.985435215946844e-2;
t17 = t2.*4.983850992823741e-3;
t18 = t3.*4.983850992823741e-3;
t6 = cos(t5);
t7 = sin(t5);
t19 = -t17;
t20 = t11+t18;
t8 = t6.^2;
t9 = t7.^2;
t21 = t12+t19;
t22 = abs(t20);
t10 = 1.0./t8;
t13 = t8+t9;
t23 = abs(t21);
t14 = t9.*t10;
t16 = 1.0./t13;
t15 = t14+1.0;
vM_total_sym = -fi12_dot.*((1.0./sqrt(t22.^2+t23.^2).*(t21.*t22.*sign(t20).*2.0-t20.*t23.*sign(t21).*2.0))./2.0+(t8.*t15.*t16)./5.0e+1)+(fi13_dot.*t8.*t15.*t16)./5.0e+1;
end
