function out1 = M_TRIPB_CMED_Q(fi12,fi13)
%M_TRIPB_CMED_Q
%    OUT1 = M_TRIPB_CMED_Q(FI12,FI13)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-May-2025 15:34:10

t2 = cos(fi12);
t3 = sin(fi12);
t4 = -fi13;
t5 = fi12+t4;
t11 = t2.*3.985435215946844e-2;
t12 = t3.*3.985435215946844e-2;
t17 = t2.*4.983850992823741e-3;
t18 = t3.*4.983850992823741e-3;
t6 = cos(t5);
t7 = sin(t5);
t19 = -t17;
t21 = t11+t18;
t8 = t6.^2;
t9 = t7.^2;
t22 = t12+t19;
t23 = abs(t21);
t10 = 1.0./t8;
t13 = t8+t9;
t24 = abs(t22);
t14 = t9.*t10;
t16 = 1.0./t13;
t15 = t14+1.0;
t20 = (t8.*t15.*t16)./5.0e+1;
out1 = [t20+(1.0./sqrt(t23.^2+t24.^2).*(t22.*t23.*sign(t21).*2.0-t21.*t24.*sign(t22).*2.0))./2.0;-t20];
end
